[2021-12-16 11:17:32,806] {processor.py:163} INFO - Started process (PID=41) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:17:32,808] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:17:32,814] {logging_mixin.py:109} INFO - [2021-12-16 11:17:32,814] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:17:32,935] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:17:37,403] {logging_mixin.py:109} INFO - [2021-12-16 11:17:37,403] {providers_manager.py:156} WARNING - Exception when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package: No module named 'plyvel'
[2021-12-16 11:17:38,776] {logging_mixin.py:109} INFO - [2021-12-16 11:17:38,776] {providers_manager.py:156} WARNING - Exception when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package: No module named 'plyvel'
[2021-12-16 11:17:38,801] {logging_mixin.py:109} INFO - [2021-12-16 11:17:38,801] {manager.py:496} INFO - Created Permission View: can read on DAG:example_trigger_target_dag
[2021-12-16 11:17:38,810] {logging_mixin.py:109} INFO - [2021-12-16 11:17:38,810] {manager.py:496} INFO - Created Permission View: can edit on DAG:example_trigger_target_dag
[2021-12-16 11:17:38,811] {logging_mixin.py:109} INFO - [2021-12-16 11:17:38,811] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:17:38,818] {logging_mixin.py:109} INFO - [2021-12-16 11:17:38,818] {dag.py:2415} INFO - Creating ORM DAG for example_trigger_target_dag
[2021-12-16 11:17:38,829] {logging_mixin.py:109} INFO - [2021-12-16 11:17:38,829] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:17:38,846] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 6.055 seconds
[2021-12-16 11:18:09,112] {processor.py:163} INFO - Started process (PID=361) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:18:09,114] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:18:09,116] {logging_mixin.py:109} INFO - [2021-12-16 11:18:09,115] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:18:09,149] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:18:09,159] {logging_mixin.py:109} INFO - [2021-12-16 11:18:09,159] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:18:09,176] {logging_mixin.py:109} INFO - [2021-12-16 11:18:09,176] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:18:09,187] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.080 seconds
[2021-12-16 11:18:39,584] {processor.py:163} INFO - Started process (PID=431) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:18:39,587] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:18:39,588] {logging_mixin.py:109} INFO - [2021-12-16 11:18:39,588] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:18:39,622] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:18:39,633] {logging_mixin.py:109} INFO - [2021-12-16 11:18:39,633] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:18:39,652] {logging_mixin.py:109} INFO - [2021-12-16 11:18:39,652] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:18:39,663] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.083 seconds
[2021-12-16 11:19:09,742] {processor.py:163} INFO - Started process (PID=501) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:19:09,744] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:19:09,745] {logging_mixin.py:109} INFO - [2021-12-16 11:19:09,745] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:19:09,776] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:19:09,786] {logging_mixin.py:109} INFO - [2021-12-16 11:19:09,786] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:19:09,800] {logging_mixin.py:109} INFO - [2021-12-16 11:19:09,800] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:19:09,808] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.069 seconds
[2021-12-16 11:19:39,928] {processor.py:163} INFO - Started process (PID=561) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:19:39,930] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:19:39,931] {logging_mixin.py:109} INFO - [2021-12-16 11:19:39,931] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:19:39,964] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:19:39,976] {logging_mixin.py:109} INFO - [2021-12-16 11:19:39,976] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:19:39,994] {logging_mixin.py:109} INFO - [2021-12-16 11:19:39,994] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:19:40,005] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.080 seconds
[2021-12-16 11:20:10,171] {processor.py:163} INFO - Started process (PID=622) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:20:10,173] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:20:10,175] {logging_mixin.py:109} INFO - [2021-12-16 11:20:10,175] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:20:10,213] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:20:10,250] {logging_mixin.py:109} INFO - [2021-12-16 11:20:10,250] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:20:10,271] {logging_mixin.py:109} INFO - [2021-12-16 11:20:10,271] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:20:10,282] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.116 seconds
[2021-12-16 11:20:40,701] {processor.py:163} INFO - Started process (PID=681) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:20:40,703] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:20:40,704] {logging_mixin.py:109} INFO - [2021-12-16 11:20:40,704] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:20:40,737] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:20:40,750] {logging_mixin.py:109} INFO - [2021-12-16 11:20:40,750] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:20:40,769] {logging_mixin.py:109} INFO - [2021-12-16 11:20:40,769] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:20:40,780] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.084 seconds
[2021-12-16 11:21:11,170] {processor.py:163} INFO - Started process (PID=750) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:21:11,172] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:21:11,173] {logging_mixin.py:109} INFO - [2021-12-16 11:21:11,173] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:21:11,205] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:21:11,215] {logging_mixin.py:109} INFO - [2021-12-16 11:21:11,215] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:21:11,232] {logging_mixin.py:109} INFO - [2021-12-16 11:21:11,232] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:21:11,241] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.076 seconds
[2021-12-16 11:21:41,485] {processor.py:163} INFO - Started process (PID=810) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:21:41,487] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:21:41,488] {logging_mixin.py:109} INFO - [2021-12-16 11:21:41,488] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:21:41,514] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:21:41,523] {logging_mixin.py:109} INFO - [2021-12-16 11:21:41,523] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:21:41,537] {logging_mixin.py:109} INFO - [2021-12-16 11:21:41,537] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:21:41,546] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.065 seconds
[2021-12-16 11:22:11,914] {processor.py:163} INFO - Started process (PID=879) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:22:11,915] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:22:11,916] {logging_mixin.py:109} INFO - [2021-12-16 11:22:11,916] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:22:11,941] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:22:11,949] {logging_mixin.py:109} INFO - [2021-12-16 11:22:11,949] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:22:11,964] {logging_mixin.py:109} INFO - [2021-12-16 11:22:11,964] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:22:11,973] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.063 seconds
[2021-12-16 11:22:42,302] {processor.py:163} INFO - Started process (PID=941) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:22:42,305] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:22:42,306] {logging_mixin.py:109} INFO - [2021-12-16 11:22:42,306] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:22:42,335] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:22:42,349] {logging_mixin.py:109} INFO - [2021-12-16 11:22:42,349] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:22:42,370] {logging_mixin.py:109} INFO - [2021-12-16 11:22:42,369] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:22:42,379] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.082 seconds
[2021-12-16 11:23:12,604] {processor.py:163} INFO - Started process (PID=1010) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:23:12,607] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:23:12,608] {logging_mixin.py:109} INFO - [2021-12-16 11:23:12,608] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:23:12,639] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:23:12,650] {logging_mixin.py:109} INFO - [2021-12-16 11:23:12,650] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:23:12,666] {logging_mixin.py:109} INFO - [2021-12-16 11:23:12,665] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:23:12,674] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.073 seconds
[2021-12-16 11:23:42,907] {processor.py:163} INFO - Started process (PID=1079) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:23:42,909] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:23:42,910] {logging_mixin.py:109} INFO - [2021-12-16 11:23:42,910] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:23:42,945] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:23:42,957] {logging_mixin.py:109} INFO - [2021-12-16 11:23:42,957] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:23:42,976] {logging_mixin.py:109} INFO - [2021-12-16 11:23:42,976] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:23:42,988] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.086 seconds
[2021-12-16 11:24:13,575] {processor.py:163} INFO - Started process (PID=1139) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:24:13,577] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:24:13,579] {logging_mixin.py:109} INFO - [2021-12-16 11:24:13,579] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:24:13,611] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:24:13,621] {logging_mixin.py:109} INFO - [2021-12-16 11:24:13,621] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:24:13,637] {logging_mixin.py:109} INFO - [2021-12-16 11:24:13,637] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:24:13,646] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.076 seconds
[2021-12-16 11:24:44,387] {processor.py:163} INFO - Started process (PID=1209) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:24:44,389] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:24:44,390] {logging_mixin.py:109} INFO - [2021-12-16 11:24:44,390] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:24:44,420] {processor.py:637} INFO - DAG(s) dict_keys(['example_trigger_target_dag']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:24:44,431] {logging_mixin.py:109} INFO - [2021-12-16 11:24:44,431] {dag.py:2396} INFO - Sync 1 DAGs
[2021-12-16 11:24:44,446] {logging_mixin.py:109} INFO - [2021-12-16 11:24:44,446] {dag.py:2928} INFO - Setting next_dagrun for example_trigger_target_dag to None
[2021-12-16 11:24:44,456] {processor.py:171} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py took 0.074 seconds
[2021-12-16 11:25:14,915] {processor.py:163} INFO - Started process (PID=1270) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:25:14,917] {processor.py:625} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py for tasks to queue
[2021-12-16 11:25:14,918] {logging_mixin.py:109} INFO - [2021-12-16 11:25:14,918] {dagbag.py:500} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_trigger_target_dag.py
[2021-12-16 11:25:14,937] {processor.py:174} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "postgres" (172.21.0.3) and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 168, in _run_file_processor
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 634, in process_file
    self._deactivate_missing_dags(session, dagbag, file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 670, in _deactivate_missing_dags
    .update({DagModel.is_active: False}, synchronize_session="fetch")
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 4063, in update
    update_op.exec_()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1696, in exec_
    self._do_pre_synchronize()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1806, in _do_pre_synchronize
    select_stmt, mapper=self.mapper, params=query._params
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1295, in execute
    return self._connection_for_bind(bind, close_with_result=True).execute(
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "postgres" (172.21.0.3) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/13/e3q8)
